version: 2.1

orbs:
  slack: circleci/slack@3.4.2

aliases:
  - &golang_image_version "1.12"
  - &gh_image_version "0.13"
  - &workspace_root ~/repo

commands:
  # Must be the last step in a job
  notify_slack:
    description: "Notify via Slack"
    steps:
      - slack/status:
          fail_only: true
          only_for_branches: master
          # Webhook URL defined as $SLACK_WEBHOOK in CircleCI project settings

executors:
  golang:
    parameters:
      golang_image_version:
        type: string
        default: *golang_image_version
    docker:
      - image: circleci/golang:<< parameters.golang_image_version >>
    working_directory: *workspace_root

  gh_release:
    parameters:
      gh_image_version:
        type: string
        default: *gh_image_version
    docker:
      - image: cibuilds/github:<< parameters.gh_image_version >>
    working_directory: *workspace_root

jobs:
  build:
    executor: golang
    steps:
      - checkout
      - run: go version
      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "go.sum" }}
      - run: go mod download
      - save_cache:
          key: go-mod-v1-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run: make build
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - bin/*
      - notify_slack

  release:
    executor: gh_release
    environment:
      ARTIFACT: bin/s3downloader-linux-amd64
      PROJECT: voltti/s3-downloader
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: Compute checksum for release
          command: sha256sum "$ARTIFACT" > ./"$ARTIFACT".sha256
      - run:
          name: Publish release in GitHub
          command: |
            ghr -t "${GITHUB_TOKEN}" \
              -u "${CIRCLE_PROJECT_USERNAME}" \
              -r "${CIRCLE_PROJECT_REPONAME}" \
              -c "${CIRCLE_SHA1}" \
              -n "${CIRCLE_TAG}" \
              -b "$(git tag -l --format='%(contents)' "${CIRCLE_TAG}")" \
              -delete \
              "${CIRCLE_TAG}" ./bin/
      - notify_slack

workflows:
  version: 2
  build_and_release:
    jobs:
      - build:
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+$/
      - release:
          context: org-global
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+$/
