#!/bin/bash

set -euo pipefail

cd "$( dirname "${BASH_SOURCE[0]}")/.."

export TAG="${GITHUB_REF#refs/tags/}"

sha256sum bin/s3downloader-linux-amd64 > ./bin/s3downloader-linux-amd64.sha256

gh release create "$TAG" ./bin/* \
    --title "$TAG" \
    --notes "$(git tag -l --format='%(contents)' "$TAG")"
